'use strict';

/**
 * @ngdoc function
 * @name cdcApp.controller:HeaderCtrl
 * @description
 * # HeaderCtrl
 * Controller of the cdcApp
 */
angular.module('cdcApp')
  .controller('HeaderCtrl', function ($scope) {
    $scope.search = function (){
      console.log('title', $scope.query);
    };

    // Manual List for Typeahead
    var diseases = [
      'Acute Disseminated Encephalomyelitis (ADEM)',
      'Acute necrotizing hemorrhagic leukoencephalitis',
      'Addison’s disease',
      'Agammaglobulinemia',
      'Alopecia areata',
      'Amyloidosis',
      'Ankylosing spondylitis',
      'Anti-GBM/Anti-TBM nephritis',
      'Antiphospholipid syndrome (APS)',
      'Autoimmune angioedema',
      'Autoimmune aplastic anemia',
      'Autoimmune dysautonomia',
      'Autoimmune hepatitis',
      'Autoimmune hyperlipidemia',
      'Autoimmune immunodeficiency',
      'Autoimmune inner ear disease (AIED)',
      'Autoimmune myocarditis',
      'Autoimmune oophoritis',
      'Autoimmune pancreatitis',
      'Autoimmune retinopathy',
      'Autoimmune thrombocytopenic purpura (ATP)',
      'Autoimmune thyroid disease',
      'Autoimmune urticaria',
      'Axonal & neuronal neuropathies',
      'Balo disease',
      'Behcet’s disease',
      'Bullous pemphigoid',
      'Cardiomyopathy',
      'Castleman disease',
      'Celiac disease',
      'Chagas disease',
      'Chronic fatigue syndrome**',
      'Chronic inflammatory demyelinating polyneuropathy (CIDP)',
      'Chronic recurrent multifocal ostomyelitis (CRMO)',
      'Churg-Strauss syndrome',
      'Cicatricial pemphigoid/benign mucosal pemphigoid',
      'Crohn’s disease',
      'Cogans syndrome',
      'Cold agglutinin disease',
      'Congenital heart block',
      'Coxsackie myocarditis',
      'CREST disease',
      'Essential mixed cryoglobulinemia',
      'Demyelinating neuropathies',
      'Dermatitis herpetiformis',
      'Dermatomyositis',
      'Devic’s disease (neuromyelitis optica)',
      'Discoid lupus',
      'Dressler’s syndrome',
      'Endometriosis',
      'Eosinophilic esophagitis',
      'Eosinophilic fasciitis',
      'Erythema nodosum',
      'Experimental allergic encephalomyelitis',
      'Evans syndrome',
      'Fibromyalgia**',
      'Fibrosing alveolitis',
      'Giant cell arteritis (temporal arteritis)',
      'Giant cell myocarditis',
      'Glomerulonephritis',
      'Goodpasture’s syndrome',
      'Granulomatosis with Polyangiitis (GPA) (formerly called Wegener’s Granulomatosis)',
      'Graves’ disease',
      'Guillain-Barre syndrome',
      'Hashimoto’s encephalitis',
      'Hashimoto’s thyroiditis',
      'Hemolytic anemia',
      'Henoch-Schonlein purpura',
      'Herpes gestationis',
      'Hypogammaglobulinemia',
      'Idiopathic thrombocytopenic purpura (ITP)',
      'IgA nephropathy',
      'IgG4-related sclerosing disease',
      'Immunoregulatory lipoproteins',
      'Inclusion body myositis',
      'Interstitial cystitis',
      'Juvenile arthritis',
      'Juvenile diabetes (Type 1 diabetes)',
      'Juvenile myositis',
      'Kawasaki syndrome',
      'Lambert-Eaton syndrome',
      'Leukocytoclastic vasculitis',
      'Lichen planus',
      'Lichen sclerosus',
      'Ligneous conjunctivitis',
      'Linear IgA disease (LAD)',
      'Lupus (SLE)',
      'Lyme disease',
      'Meniere’s disease',
      'Microscopic polyangiitis',
      'Mixed connective tissue disease (MCTD)',
      'Mooren’s ulcer',
      'Mucha-Habermann disease',
      'Multiple sclerosis',
      'Myasthenia gravis',
      'Myositis',
      'Narcolepsy',
      'Neuromyelitis optica (Devic’s)',
      'Neutropenia',
      'Ocular cicatricial pemphigoid',
      'Optic neuritis',
      'Palindromic rheumatism',
      'PANDAS (Pediatric Autoimmune Neuropsychiatric Disorders Associated with Streptococcus)',
      'Paraneoplastic cerebellar degeneration',
      'Paroxysmal nocturnal hemoglobinuria (PNH)',
      'Parry Romberg syndrome',
      'Parsonnage-Turner syndrome',
      'Pars planitis (peripheral uveitis)',
      'Pemphigus',
      'Peripheral neuropathy',
      'Perivenous encephalomyelitis',
      'Pernicious anemia',
      'POEMS syndrome',
      'Polyarteritis nodosa',
      'Type I',
      'Polymyalgia rheumatica',
      'Polymyositis',
      'Postmyocardial infarction syndrome',
      'Postpericardiotomy syndrome',
      'Progesterone dermatitis',
      'Primary biliary cirrhosis',
      'Primary sclerosing cholangitis',
      'Psoriasis',
      'Psoriatic arthritis',
      'Idiopathic pulmonary fibrosis',
      'Pyoderma gangrenosum',
      'Pure red cell aplasia',
      'Raynauds phenomenon',
      'Reactive Arthritis',
      'Reflex sympathetic dystrophy',
      'Reiter’s syndrome',
      'Relapsing polychondritis',
      'Restless legs syndrome',
      'Retroperitoneal fibrosis',
      'Rheumatic fever',
      'Rheumatoid arthritis',
      'Sarcoidosis',
      'Schmidt syndrome',
      'Scleritis',
      'Scleroderma',
      'Sjogren’s syndrome',
      'Sperm & testicular autoimmunity',
      'Stiff person syndrome',
      'Subacute bacterial endocarditis (SBE)',
      'Susac’s syndrome',
      'Sympathetic ophthalmia',
      'Takayasu’s arteritis',
      'Temporal arteritis/Giant cell arteritis',
      'Thrombocytopenic purpura (TTP)',
      'Tolosa-Hunt syndrome',
      'Transverse myelitis',
      'Type 1 diabetes',
      'Ulcerative colitis',
      'Undifferentiated connective tissue disease (UCTD)',
      'Uveitis',
      'Vasculitis',
      'Vesiculobullous dermatosis',
      'Vitiligo',
      'Wegener’s granulomatosis (now termed Granulomatosis with Polyangiitis (GPA)'
    ];

    // constructs the suggestion engine
    diseases = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: diseases.map(function(disease) { return { value: disease }; })
    });

    // kicks off the loading/processing of `local` and `prefetch`
    diseases.initialize();

    angular.element('#query').typeahead({
      minLength: 1,
      highlight: true,
    }, {
      name: 'diseases',
      displayKey: 'value',
      source: diseases.ttAdapter()
    });
  });
